name: eaudit
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pip
  - dbfread
  - ipykernel
  - seaborn
  - pip:
    - glob2
    - numpy
    - scikit-learn
    - scikit-plot
    - scipy
    - urllib3
